.TH HOLBERTON_SHELL 1

.SH NAME
.B Holberton Shell 
- command processor (shell)
.SH SYNOPSIS
.B ./Holberton_Shell
.SH DESCRIPTION
.B Overview \-
Holberton Shell is a command interpreter for Linux systems. It will process lines from the terminal, seperate them into arguments, and execute the appropriate program using these arguments as input.

.B exit \-
Will kill the holberton shell process and exit the user out of it, Ctrl-D will also work towards this end

.B  env \-
Will print the current environment
.SH SEE ALSO
man (1), echo (1)
